---
- include: yum.yml
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- include: apt.yml
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
        
- name: Add configuration
    template: src={{ mysql_conf_tpl }} dest={{ mysql_conf_dir[ansible_distribution] }}/{{ mysql_conf_file }} owner=root group=root mode=0644
    when: mysql_conf_tpl != 'change_me'
    notify: restart mysql 
        
- name: SQL service
    service: name=mysql state=started enabled=yes
        
- include: mysql_secure_installation.yml
    when: mysql_secure_installation and mysql_root_password is defined
