---
- name: Install dependencies YUM
    yum: name={{ item }} enablerepo=mariadb state=present
    with_items:
        - mariadb
        - mariadb-server
        - php-mysql

- name: Install MySQL python dependency for secure install 
    yum: name=MySQL-python state=present
    when: mysql_secure_installation and mysql_root_password is defined

